<a href="https://colab.research.google.com/github/aritapia19/Electronica/blob/main/nunpy_nuevo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
import matplotlib.pyplot as plt


In [3]:
lista= [31,28,29,19]

In [4]:
arr = np.array(lista)

In [5]:
arr

array([31, 28, 29, 19])

In [7]:
lista_2d=[[2,3,4],
          [3,4,5],
          [3,4,5],
          [3,4,5]]


In [8]:
arr = np.array(lista_2d)


In [9]:
arr

array([[2, 3, 4],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [10]:
arr.shape

(4, 3)

In [11]:
arr.ndim

2

In [12]:
arr.dtype


dtype('int64')

In [13]:
arr.size

12

In [15]:
arr = np.array(lista_2d, dtype= np.int16)

In [16]:
arr

array([[2, 3, 4],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]], dtype=int16)